import { Inter } from 'next/font/google'
import './globals.css'
import axios from 'axios';
axios.defaults.baseURL = 'https://nee-server.onrender.com/api/v1';
axios.defaults.withCredentials = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Mama',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
